name: Rust CI & Binary Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      # Optional: Cache dependencies (speeds up builds)
      - name: Cache Cargo dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build (Release)
        run: cargo build --release --verbose

      - name: Run tests
        run: cargo test --verbose

      # Only upload artifact if it's a push (not a PR)
      - name: Upload binary as artifact
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v4
        with:
          name: hyprfreeze-rs
          path: |
            target/release/hyprfreeze-rs*
            !target/release/build/
            !target/release/incremental/
          retention-days: 7
